name: Generic build maven with test coverage and sonar and codeql
description: 'Generic build maven with test coverage and sonar and codeql'

inputs:
  sonar_token:
    description: 'Sonar token'
    required: true
  github_token:
    description: 'github token'
    required: true
  codecov_token:
    description: 'Sonar token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: java
    - name: Build
      run: mvn --settings settings.xml clean install
      shell: bash
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
    - name: SonarCloud Scan
      run: mvn -B clean verify -Pcoverage,sonar -Dsonar.login=${{ inputs.sonar_token }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Test Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ inputs.codecov_token }}
        files: ./target/site/jacoco-aggregate/jacoco.xml