name: deploy image to server by manual trigger
on:
  workflow_dispatch:
    inputs:
      hostname:
        required: true
        description: "Hostname to deploy"
        default: "mactep.info"
      image:
        required: true
        description: "image to deploy"
        default: "earthquake-image"
      label:
        required: true
        description: "label to deploy"
        default: "nightbuild"
      container_name:
        required: true
        description: "name for container"
        default: "event-reader-nightbuild"
jobs:
  call-workflow-generic-deploy-image-to-server:
    uses: ./.github/workflows/generic-deploy-image-to-server.yml
    with:
      hostname: ${{ github.event.inputs.hostname }}
      image: ${{ github.event.inputs.image }}
      label: ${{ github.event.inputs.label }}
      container_name: ${{ github.event.inputs.container_name }}
      repository: docker.pkg.github.com/antonovdmitriy/earthquake
    secrets:
      ssh_user: ${{ secrets.STAGING_SSH_USER }}
      ssh_key: ${{ secrets.STAGING_SSH_KEY }}
      token_for_docker_auth: ${{ secrets.TOKEN_FOR_DOCKER_AUTH }}