name: Docker publish night build
on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build
      run: mvn --settings settings.xml clean install
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./event-reader
        push: true
        tags: |
          docker.pkg.github.com/${{ github.repository }}/earthquake-image:${{ github.sha }}
          docker.pkg.github.com/${{ github.repository }}/earthquake-image:nightbuild
    
      
      
