name: On image

on:
  registry_package:
    types: [ published, updated ]

jobs:
  deploy-image-to-server:
    uses: ./.github/workflows/generic-deploy-image-to-server.yml
    with:
      hostname: "mactep.info"
      container_name: earthquake-event-reader
      full_image_path: ${{ github.event.registry_package.package_version.package_url }}
      repository: ${{ github.event.registry_package.registry.url }}
    secrets:
      ssh_user: ${{ secrets.STAGING_SSH_USER }}
      ssh_key: ${{ secrets.STAGING_SSH_KEY }}
      token_for_docker_auth: ${{ secrets.TOKEN_FOR_DOCKER_AUTH }}