name: On merge pull request to develop

on:
  push:
    branches:
      - 'develop'

jobs:
  build-and-push-image-to-registry:
    runs-on: ubuntu-18.04
    permissions:
      security-events: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1
      - name: Build maven with test coverage and sonar
        uses: ./.github/actions/generic-build-maven-with-test-coverage-and-sonar/
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
      - name: Create docker image nightbuild and push to registry
        uses: ./.github/actions/build-image-and-push-to-registry/
        with:
          github_token: ${{ secrets.TOKEN_FOR_DOCKER_AUTH }}
          context: ./event-reader
          image_name: earthquake-image